changelog:
  exclude:
    labels:
      - ignore for release
    authors:
      - dependabot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking change
    - title: Features 🎉
      labels:
        - feature
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Internal 🔨
      labels:
        - internal
        - documentation
    - title: Other Changes
      labels:
        - "*"
